name: gammapy_mwl
channels:
- defaults
- conda-forge
- https://cxc.cfa.harvard.edu/conda/sherpa
dependencies:
- astropy=6.1
- astroquery=0.4.7
# - gammapy=1.3.dev726+g6c6d15956
- matplotlib=3.8.3
- numpy=1.26.4
- photutils=1.8.0
- pygtc=0.5.0
- pytest=8.1.1
- pyyaml=6.0.1
- regions=0.9
- requests=2.31.0
- scipy=1.12.0
- sherpa=4.16.0
